aliases:
  - &android
    components:
      - build-tools-28.0.3
      - android-28
      - extra-android-m2repository
      - extra-android-support

  - &android-cache
    directories:
      - ~/.cache/yarn
      - ~/.gradle/caches/modules-2
      - ~/.gradle/wrapper

  - &ios-cache
    directories:
      - ~/.rncache
      - ~/Library/Caches/Yarn

jobs:
  include:
    - stage: "build test for example"
      language: objective-c
      os: osx
      osx_image: xcode11.2
      cache: *ios-cache
      before_install:
      script:
        - nvm install node
        - brew install yarn
        - yarn add typescript
        - yarn build
        - cd ios
        - pod install --repo-update
        - cd ..
        - yarn run-ios

stages:
  - name: "build test for example"
    # if: branch = master
